import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function adminLayout({ children }) {
  return (
    <>
      <div>Admin Navbar</div>
      {children}
      <div>Admin Footer</div>
    </>
  );
}
