import React from 'react'

const about = () => {
  return (
    <div>about</div>
  )
}

export default about;
export const metadata = {
    title: "Next App About Page",
    description: "Generated by create next app",
};